import {
	Archive,
	CalendarClock,
	CalendarDays,
	Car,
	ClipboardList,
	FileText,
	HardHat,
	History,
	LayoutDashboard,
	ListOrdered,
	Route,
	School,
	Settings,
	UserCheck,
	Users,
} from "lucide-react";

export const navItems = [
	{ href: "/", label: "Dashboard", icon: LayoutDashboard },
	{ href: "/students", label: "Students", icon: Users },
	{ href: "/schools", label: "Schools", icon: School },
	{ href: "/guardians", label: "Guardians", icon: UserCheck },
	{ href: "/enrollments", label: "Enrollments", icon: FileText },
	{ href: "/calendar-rules", label: "Calendar Rules", icon: CalendarDays },
	{ href: "/attendance", label: "Attendance", icon: ClipboardList },
	{ href: "/route-management", label: "Route Management", icon: Route },
	{ href: "/route-history", label: "Route History", icon: History },
	{ href: "/vehicles", label: "Vehicles", icon: Car },
	{ href: "/staff", label: "Staff", icon: HardHat },
	{ href: "/staff-schedule", label: "Staff Schedule", icon: CalendarClock },
	{ href: "/waitlist", label: "Waitlist", icon: ListOrdered },
	{ href: "/former-students", label: "Former Students", icon: Archive },
	{ href: "/settings", label: "Settings", icon: Settings },
];
